{{- if .Values.secretObjects.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "deployment-chart.fullname" . }}-secret
spec:
  provider: aws
  secretObjects:
  - secretName: {{ .Values.secretObjects.secretName }}
    type: Opaque
    data: 
    - objectName: secret-token
      key: ENV
  parameters:
    objects: |
      - objectName: {{ .Values.secretObjects.secretName }}
        objectType: secretsmanager
        objectAlias: secret-token
{{- end }}